name: Infra Deploy 

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        default: "validate"
        type: choice
        options:
          - validate
          - plan
          - apply

env:
  TF_PROFILE: portfolio  
  TF_VAR_region: "ap-south-1"  

run-name: Performed ${{ inputs.action }} by @${{ github.actor }}

jobs:
  deploy_infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.9.8"  

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.TF_VAR_region }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Action
      run: |
        ACTION=${{ github.event.inputs.action }}
        echo "Running Terraform action: $ACTION"
        
        # Run the appropriate Terraform action based on input
        if [ "$ACTION" == "validate" ]; then
          terraform validate
        elif [ "$ACTION" == "plan" ]; then
          terraform plan -out=tfplan
        elif [ "$ACTION" == "apply" ]; then
          terraform apply -auto-approve tfplan
        else
          echo "Invalid action. Please choose 'validate', 'plan', or 'apply'."
          exit 1
        fi
