name: Infra Deploy 

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        default: "validate"
        type: choice
        options:
          - validate
          - plan
          - apply

env:
  # TF_PROFILE: portfolio  
  TF_VAR_region: "ap-south-1"  

run-name: Performed Terraform ${{ inputs.action }} by @${{ github.actor }}

jobs:
  deploy_infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.9.8"  

    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
        unzip -q /tmp/awscliv2.zip -d /tmp
        sudo /tmp/aws/install --update


    - name: Configure AWS CLI
      run: |
        echo "Configuring AWS CLI..."
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $AWS_PROFILE
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $AWS_PROFILE
        aws configure set region $TF_VAR_region --profile $AWS_PROFILE
        echo "AWS CLI configured with profile: $AWS_PROFILE"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_region: ${{ env.TF_VAR_region }}
        AWS_PROFILE: "portfolio"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Action
      run: |
        ACTION=${{ github.event.inputs.action }}
        echo "Running Terraform action: $ACTION"
        
        # Run the appropriate Terraform action based on input
        if [ "$ACTION" == "validate" ]; then
          terraform validate
        elif [ "$ACTION" == "plan" ]; then
          terraform plan 
        elif [ "$ACTION" == "apply" ]; then
          terraform apply -auto-approve 
        else
          echo "Invalid action. Please choose 'validate', 'plan', or 'apply'."
          exit 1
        fi
